annotations:
  vendor: ViaPath
apiVersion: v2
description: A Helm chart for Kubernetes
maintainers:
- name: Ed Yablonsky
  email: eduard.yablonskyy@viapath.com
name: viapathlib
sources:
- https://gitlab.gtl.net/devops/helmcharts/library
type: library
version: 0.1.0
