{{- define "viapathlib.deployment" -}}
{{- $locals := dict }}
{{- with .Values.service }}
  {{- with .livenessProbe }}
    {{- $locals = set $locals "livenessProbe" . -}}
  {{- end }}
  {{- with .readinessProbe }}
    {{- $locals = set $locals "readinessProbe" . -}}
  {{- end }}
  {{- with .startupProbe }}
    {{- $locals = set $locals "startupProbe" . -}}
  {{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
        image: {{
          (list
            (list
              .Values.image.registry
              .Values.image.repository
              | compact | join "/"
            )
            (.Values.image.tag | default .Chart.AppVersion)
            | compact | join ":"
          ) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        envFrom:
        - configMapRef:
            name: {{ list (include "chart.fullname" .) "envs" | join "-" }}
        - secretRef:
            name: {{ list (include "chart.fullname" .) "envs" | join "-" }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        {{- with $locals.livenessProbe }}
        livenessProbe:
        {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
        {{- with $locals.readinessProbe }}
        readinessProbe:
          {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- . | toYaml | trim | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
