{{- define "viapathlib.secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ list (include "chart.fullname" .) "envs" | join "-" }}
type: Opaque
{{- with .Values.secretEnvs }}
stringData:
{{- range $index, $element := . }}
  {{ $index }}: {{ $element | quote }}
{{- end }}
{{- end }}
{{- end }}
